name: 'Custom Amazon Bedrock Agent Action'
description: 'This GitHub Action leverages Amazon Bedrock Agent to analyze files in a pull request (PR) and provide feedback.'
author: 'John Reilly Pospos <johnreilly.pospos@gmail.com>'
inputs:
  agent_id:
    description: 'The ID of the Bedrock Agent to use.'
    required: true
  agent_alias_id:
    description: 'The alias ID of the Bedrock Agent to use.'
    required: true
  action_prompt:
    description: 'The prompt to send to the Bedrock Agent for analysis.'
    required: true
    default: 'Given the relevant code changes above, provide a detailed analysis including potential improvements and security considerations.'
  ignore_patterns:
    description: 'Comma-separated list of glob patterns to ignore (similar to .gitignore).'
    required: true
    default: '**/*.md,docs/**,.github/**'
  logging_level:
    description: 'Logging level for the action. Set to "debug" for detailed logs or "info" for general logs.'
    required: false
    default: 'info'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  color: 'blue'
  icon: 'code'
